ajout de login , register, modif api
Pyracantharia/FADEC pull request #5
Opened 2024-02-04 16:32 UTC by Pyracantharia

ajout de login , register, modif api

MODIF API ATTENTION A VERIFIER

2024-02-09 18:22 UTC, deathfal requested changes

2024-02-09 18:22 UTC, deathfal commented on www/api/controllers/users/post.php
> +    // $user->id = $request["id"];
We should let the API generate the id not the DB

2024-02-09 18:22 UTC, deathfal commented on www/api/models/users.php
> -        $id = htmlspecialchars(strip_tags($this->id));
TODO

2024-02-09 18:22 UTC, deathfal commented on www/api/models/users.php
> -        $stmt->bindParam(":id", $id);
TODO

2024-02-17 14:52 UTC, closed without merging

2024-02-17 14:52 UTC, Pyracantharia commented
sa ne corresponder pas a ce qu'on veut